---
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 30 days (based on index name), for filebeat-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: filebeat-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 7
      exclude:
  2:
    action: delete_indices
    description: >-
      Delete indices matching the prefix tomcat in excess of
      300GB of data (75% of 400GB) , starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: True # Disabled until further testing
    filters:
    - filtertype: pattern
      kind: prefix
      value: metricbeat-
    - filtertype: space
      disk_space: 300
      use_age: True
      source: creation_date
